import { FormEvent, useEffect, useRef, useState } from "react";
import { ArrowLeft, CheckCheck, MessageCircle, MoreHorizontal, Search, Send, Users } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { State } from "../../components/ui";
import { useAuth } from "../../contexts/AuthContext";
import { useApi } from "../../hooks/useApi";
import { supabase } from "../../lib/supabase";
import { post } from "../../services/api";
type Person={id:string;full_name:string;avatar_url:string|null;role:string;last_read_at?:string|null};
type Conversation={id:string;subject:string;last_message_at:string;last_message_preview:string;unread:boolean;members:Person[]};
type Chat={conversation:Conversation;members:Person[];messages:{id:string;sender_id:string;content:string;created_at:string}[]};
const avatar=(person?:Person)=>person?.avatar_url||`https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent(person?.full_name||"MediaHub")}`;
export function MessengerPage(){const {id}=useParams(),nav=useNavigate(),{profile}=useAuth();const [search,setSearch]=useState("");const inbox=useApi<Conversation[]>("/messages");const chat=useApi<Chat>(id?`/messages/${id}`:null);const end=useRef<HTMLDivElement>(null);const selected=chat.data;const peer=(c:Conversation|Chat["conversation"])=>c.members?.find(x=>x.id!==profile?.id)||c.members?.[0];
 useEffect(()=>{const realtime=supabase;if(!id||!realtime)return;const channel=realtime.channel(`conversation:${id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"conversation_messages",filter:`conversation_id=eq.${id}`},()=>{chat.reload();inbox.reload()}).subscribe();return()=>{void realtime.removeChannel(channel)}},[id]);
 useEffect(()=>{if(id&&chat.data){void post(`/messages/${id}/read`).then(inbox.reload);end.current?.scrollIntoView({behavior:"smooth"})}},[id,chat.data?.messages.length]);
 async function send(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!id)return;const form=e.currentTarget,input=form.elements.namedItem("message") as HTMLTextAreaElement,value=input.value.trim();if(!value)return;input.value="";try{await post(`/messages/${id}/messages`,{content:value,attachments:[]});chat.reload();inbox.reload()}catch{input.value=value}}
 const rows=(inbox.data||[]).filter(c=>`${c.subject} ${peer(c)?.full_name}`.toLowerCase().includes(search.toLowerCase()));
 return <main className={`messenger ${id?"chat-open":""}`}><aside className="messenger-list"><header><div><h1>Đoạn chat</h1><button aria-label="Tùy chọn"><MoreHorizontal/></button></div><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm kiếm trên Messenger"/></label></header><State query={inbox}><div className="conversation-list">{rows.map(c=>{const p=peer(c);return <button className={c.id===id?"active":""} key={c.id} onClick={()=>nav(`/messages/${c.id}`)}><span className="avatar-wrap"><img src={avatar(p)} alt=""/><i/></span><span><strong>{p?.full_name||c.subject}</strong><small className={c.unread?"unread":""}>{c.last_message_preview||"Bắt đầu cuộc trò chuyện"} · {relative(c.last_message_at)}</small></span>{c.unread&&<b className="unread-dot"/>}</button>})}{!rows.length&&<div className="no-conversations"><MessageCircle/><p>Chưa có cuộc trò chuyện</p></div>}</div></State></aside><section className="messenger-chat">{!id?<div className="messenger-welcome"><span><MessageCircle/></span><h2>Tin nhắn của bạn</h2><p>Chọn một cuộc trò chuyện hoặc nhắn tin cho Creator từ trang khám phá.</p></div>:<State query={chat}>{selected&&<><header className="chat-header"><button className="back-chat" onClick={()=>nav("/messages")}><ArrowLeft/></button><img src={avatar(peer(selected.conversation))} alt=""/><div><strong>{peer(selected.conversation)?.full_name||selected.conversation.subject}</strong><small><i/> Đang hoạt động</small></div><button aria-label="Thành viên"><Users/></button></header><div className="message-history"><div className="chat-intro"><img src={avatar(peer(selected.conversation))} alt=""/><h2>{peer(selected.conversation)?.full_name}</h2><p>Các tin nhắn và cuộc gọi được bảo vệ trong hệ thống MediaHub.</p></div>{selected.messages.map((m,i)=>{const mine=m.sender_id===profile?.id;const sender=selected.members.find(x=>x.id===m.sender_id);const next=selected.messages[i+1];return <div className={`message-row ${mine?"mine":""}`} key={m.id}>{!mine&&<img src={avatar(sender)} alt=""/>}<div><p>{m.content}</p>{(!next||next.sender_id!==m.sender_id)&&<small>{new Date(m.created_at).toLocaleTimeString("vi-VN",{hour:"2-digit",minute:"2-digit"})}{mine&&<CheckCheck/>}</small>}</div></div>})}<div ref={end}/></div><form className="message-composer" onSubmit={send}><textarea name="message" rows={1} maxLength={5000} placeholder="Aa" onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}}/><button aria-label="Gửi tin nhắn"><Send/></button></form></>}</State>}</section></main>}
function relative(value:string){const minutes=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));if(minutes<1)return"vừa xong";if(minutes<60)return`${minutes} phút`;if(minutes<1440)return`${Math.floor(minutes/60)} giờ`;return`${Math.floor(minutes/1440)} ngày`}
