// Generated by scripts/generate-models.mjs from 001_mediahub.sql. Do not edit by hand.
export type Notification = {
  id: string;
  user_id: string;
  title: string;
  message: string;
  type: string;
  read_at: string | null;
  created_at: string | null;
};
export type NotificationInsert = {
  id?: string;
  user_id: string;
  title: string;
  message: string;
  type: string;
  read_at?: string | null;
  created_at?: string | null;
};
export type NotificationUpdate = Partial<NotificationInsert>;
