// Generated by scripts/generate-models.mjs from 001_mediahub.sql. Do not edit by hand.
export type ProjectService = {
  id: string;
  project_id: string;
  service_id: string;
  quantity: number;
  notes: string | null;
  created_at: string | null;
};
export type ProjectServiceInsert = {
  id?: string;
  project_id: string;
  service_id: string;
  quantity?: number;
  notes?: string | null;
  created_at?: string | null;
};
export type ProjectServiceUpdate = Partial<ProjectServiceInsert>;
