// Generated by scripts/generate-models.mjs from 001_mediahub.sql. Do not edit by hand.
export type QuotationItem = {
  id: string;
  quotation_id: string;
  service_id: string | null;
  description: string;
  quantity: number;
  unit_price: number;
  total: number;
};
export type QuotationItemInsert = {
  id?: string;
  quotation_id: string;
  service_id?: string | null;
  description: string;
  quantity: number;
  unit_price: number;
  total: number;
};
export type QuotationItemUpdate = Partial<QuotationItemInsert>;
