// Generated by scripts/generate-models.mjs from 001_mediahub.sql. Do not edit by hand.
export type Testimonial = {
  id: string;
  review_id: string;
  content: string;
  status: "PENDING" | "APPROVED" | "REJECTED";
  published_at: string | null;
};
export type TestimonialInsert = {
  id?: string;
  review_id: string;
  content: string;
  status?: "PENDING" | "APPROVED" | "REJECTED";
  published_at?: string | null;
};
export type TestimonialUpdate = Partial<TestimonialInsert>;
