import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// The migration is the source of truth; generated rows preserve SQL nullability.
const root = fileURLToPath(new URL('../', import.meta.url));
const sql = fs.readFileSync(path.join(root, '../supabase/migrations/001_mediahub.sql'), 'utf8');
const names = { profiles: 'Profile', customers: 'Customer', employees: 'Employee', services: 'Service', projects: 'Project', project_services: 'ProjectService', quotations: 'Quotation', quotation_items: 'QuotationItem', project_files: 'ProjectFile', project_status_history: 'ProjectStatusHistory', deliverables: 'Deliverable', revision_requests: 'RevisionRequest', reviews: 'Review', testimonials: 'Testimonial', invoices: 'Invoice', notifications: 'Notification', portfolio: 'Portfolio' };
function columns(text) {
  let depth = 0, quoted = false, start = 0;
  const result = [];
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (ch === "'") quoted = !quoted;
    if (!quoted) {
      if (ch === '(') depth++;
      if (ch === ')') depth--;
      if (ch === ',' && depth === 0) { result.push(text.slice(start, i).trim()); start = i + 1; }
    }
  }
  result.push(text.slice(start).trim());
  return result.filter(c => !/^(unique|constraint|check|primary|foreign)\b/.test(c));
}
const outputs = new Map();
const tables = [...sql.matchAll(/create table public\.(\w+)\(([^;]+)\);/g)];
if (tables.length !== Object.keys(names).length) throw new Error('Update model mapping for new or removed tables.');
const banner = '// Generated by scripts/generate-models.mjs from 001_mediahub.sql. Do not edit by hand.\n';
let index = banner, imports = '', entries = '';
for (const [, table, body] of tables) {
  const name = names[table], filename = table.replaceAll('_', '-') + '.model';
  const fields = columns(body).map(def => {
    const [column, sqlType] = def.split(/\s+/);
    const enumMatch = def.match(new RegExp(`check\\(${column} in \\(([^)]+)\\)`));
    let type = enumMatch ? [...enumMatch[1].matchAll(/'([^']+)'/g)].map(x => JSON.stringify(x[1])).join(' | ') : sqlType === 'text[]' ? 'string[]' : /^(numeric|integer|bigint)/.test(sqlType) ? 'number' : sqlType === 'boolean' ? 'boolean' : 'string';
    const nullable = !/not null|primary key/.test(def);
    if (nullable) type += ' | null';
    const optional = nullable || /\bdefault\b/.test(def);
    const reference = def.match(/references (?:public\.)?(\w+)\((\w+)\)/);
    return { column, type, optional, reference, unique: /\bunique\b/.test(def) };
  });
  const row = fields.map(f => `  ${f.column}: ${f.type};`).join('\n');
  const insert = fields.map(f => `  ${f.column}${f.optional ? '?' : ''}: ${f.type};`).join('\n');
  outputs.set(`src/models/${filename}.ts`, `${banner}export type ${name} = {\n${row}\n};\nexport type ${name}Insert = {\n${insert}\n};\nexport type ${name}Update = Partial<${name}Insert>;\n`);
  index += `export type { ${name}, ${name}Insert, ${name}Update } from './${filename}.js';\n`;
  imports += `import type { ${name}, ${name}Insert, ${name}Update } from './${filename}.js';\n`;
  const relationships = fields.filter(f => f.reference && f.reference[1] !== 'users').map(f => `{ foreignKeyName: '${table}_${f.column}_fkey'; columns: ['${f.column}']; isOneToOne: ${f.unique}; referencedRelation: '${f.reference[1]}'; referencedColumns: ['${f.reference[2]}'] }`).join(', ');
  entries += `    ${table}: { Row: ${name}; Insert: ${name}Insert; Update: ${name}Update; Relationships: [${relationships}] };\n`;
}
outputs.set('src/models/index.ts', index + "export type { Database, TableName, Row, Insert, Update, Json } from './database.types.js';\nexport type { Identity } from './identity.model.js';\nexport type { DashboardReport, Paginated } from './report.model.js';\n");
outputs.set('src/models/database.types.ts', `${banner}${imports}import type { DashboardReport } from './report.model.js';\nexport type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];\nexport type Database = { public: { Tables: {\n${entries}  }; Views: { [_ in never]: never }; Functions: {\n    project_action: { Args: { actor_id: string; pid: string | null; action: string; payload?: Json }; Returns: { id: string } };\n    dashboard_report: { Args: { actor_id: string }; Returns: DashboardReport };\n    is_admin: { Args: Record<string, never>; Returns: boolean };\n    owns_project: { Args: { pid: string }; Returns: boolean };\n  }; Enums: { [_ in never]: never }; CompositeTypes: { [_ in never]: never }; } };\nexport type TableName = keyof Database['public']['Tables'];\nexport type Row<T extends TableName> = Database['public']['Tables'][T]['Row'];\nexport type Insert<T extends TableName> = Database['public']['Tables'][T]['Insert'];\nexport type Update<T extends TableName> = Database['public']['Tables'][T]['Update'];\n`);
let mismatches = 0;
for (const [file, content] of outputs) {
  const target = path.join(root, file);
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8').replaceAll('\r\n', '\n') !== content) { console.error(`Outdated model: ${file}`); mismatches++; }
  } else { fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, content); }
}
if (mismatches) process.exitCode = 1;
else console.log(`${process.argv.includes('--check') ? 'Verified' : 'Generated'} ${tables.length} table models and database types.`);
