import express,{type Request,type Response,type NextFunction} from 'express';
import cors from 'cors';import helmet from 'helmet';import {rateLimit} from 'express-rate-limit';import multer from 'multer';import {z} from 'zod';import {randomUUID} from 'node:crypto';
import {db,result,ApiError} from './db.js';import {authenticate,requireRole} from './middleware.js';import {canAccess} from './domain.js';import {uuid,projectSchema,quoteSchema,reviewSchema,revisionSchema,statusSchema,resources} from './validators.js';
export const app=express();
app.use(helmet(),cors({origin:(process.env.CORS_ORIGIN??'http://localhost:5173').split(',')}),express.json({limit:'1mb'}),rateLimit({windowMs:60000,limit:180,standardHeaders:'draft-8',legacyHeaders:false,message:{success:false,error:{code:'RATE_LIMIT',message:'Vui lòng thử lại sau.'}}}));
app.use((req,res,next)=>{const start=Date.now();res.on('finish',()=>console.info(req.method,req.path,res.statusCode,Date.now()-start));next()});
const send=(res:Response,data:unknown)=>res.json({success:true,data});
const paging=z.object({page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(100).default(20),search:z.string().max(100).default(''),status:z.string().max(40).optional(),service_id:uuid.optional(),from:z.iso.date().optional(),to:z.iso.date().optional()});
async function list(req:Request,query:any,searchField?:string){const f=paging.parse(req.query);if(f.search&&searchField)query=query.ilike(searchField,`%${f.search.replace(/[%_]/g,'')}%`);const {data,error,count}=await query.range((f.page-1)*f.limit,f.page*f.limit-1);if(error)throw new ApiError(500,'DATABASE_ERROR','Không thể tải dữ liệu.');return {items:data,total:count,page:f.page,limit:f.limit};}
async function owned(req:Request){const id=uuid.parse(req.params.id);const p=await result(db.from('projects').select('*').eq('id',id).maybeSingle());if(!p||!canAccess(req.identity.role,req.identity.customer_id,p.customer_id))throw new ApiError(404,'PROJECT_NOT_FOUND','Không tìm thấy dự án.');return p;}
async function action(req:Request,name:string,payload:unknown={}){await owned(req);return result(db.rpc('project_action',{actor_id:req.identity.id,pid:req.params.id,action:name,payload}));}
app.get('/api/health',(_req,res)=>send(res,{status:'ok'}));
for(const [route,table,field,value] of [['services','services','active',true],['portfolio','portfolio','published',true],['testimonials','testimonials','status','APPROVED']] as const){app.get(`/api/public/${route}`,async(req,res)=>send(res,await list(req,db.from(table).select('*',{count:'exact'}).eq(field,value).order(table==='testimonials'?'published_at':'created_at',{ascending:false}),table==='portfolio'?'title':undefined)));}
app.get('/api/public/portfolio/:id',async(req,res)=>{const p=await result(db.from('portfolio').select('*').eq('id',uuid.parse(req.params.id)).eq('published',true).maybeSingle());if(!p)throw new ApiError(404,'NOT_FOUND','Không tìm thấy dự án.');send(res,p)});
app.use('/api',authenticate);
app.get('/api/auth/me',(req,res)=>send(res,req.identity));
app.patch('/api/auth/me',async(req,res)=>{const body=z.object({full_name:z.string().trim().min(1).max(150),phone:z.string().max(30).optional()}).strict().parse(req.body);send(res,await result(db.from('profiles').update(body).eq('id',req.identity.id).select().single()))});
app.get('/api/notifications',async(req,res)=>send(res,await list(req,db.from('notifications').select('*',{count:'exact'}).eq('user_id',req.identity.id).order('created_at',{ascending:false}))));
app.patch('/api/notifications/:id',async(req,res)=>{z.object({}).strict().parse(req.body);send(res,await result(db.from('notifications').update({read_at:new Date().toISOString()}).eq('id',uuid.parse(req.params.id)).eq('user_id',req.identity.id).select().maybeSingle()))});
app.get('/api/customer/dashboard',requireRole('CUSTOMER'),async(req,res)=>send(res,await result(db.rpc('dashboard_report',{actor_id:req.identity.id}))));
async function projectList(req:Request){const f=paging.parse(req.query);let q=db.from('projects').select('*,customers(company_name,profiles(full_name,email)),project_services!inner(service_id)',{count:'exact'}).order('created_at',{ascending:false});if(req.identity.role==='CUSTOMER')q=q.eq('customer_id',req.identity.customer_id!);if(f.status)q=q.eq('status',f.status);if(f.service_id)q=q.eq('project_services.service_id',f.service_id);if(f.from)q=q.gte('created_at',f.from);if(f.to)q=q.lt('created_at',new Date(new Date(f.to).getTime()+86400000).toISOString());return list(req,q,'title');}
app.get('/api/projects',async(req,res)=>send(res,await projectList(req)));
app.post('/api/projects',requireRole('CUSTOMER'),async(req,res)=>{const body=projectSchema.parse(req.body);res.status(201);send(res,await result(db.rpc('project_action',{actor_id:req.identity.id,pid:null,action:'create',payload:body})))});
app.get('/api/projects/:id',async(req,res)=>{const p=await owned(req);const tables=['project_services','quotations','project_files','project_status_history','deliverables','revision_requests','invoices','reviews'];const values=await Promise.all(tables.map(t=>result(db.from(t).select(t==='quotations'?'*,quotation_items(*)':'*').eq('project_id',p.id))));send(res,{...p,...Object.fromEntries(tables.map((t,i)=>[t,values[i]]))})});
app.patch('/api/projects/:id',requireRole('CUSTOMER'),async(req,res)=>send(res,await action(req,'edit',projectSchema.parse(req.body))));
for(const [path,table] of [['history','project_status_history'],['files','project_files'],['deliverables','deliverables']] as const)app.get(`/api/projects/:id/${path}`,async(req,res)=>{await owned(req);send(res,await list(req,db.from(table).select('*',{count:'exact'}).eq('project_id',req.params.id).order('created_at',{ascending:true}))) });
for(const [path,name,schema] of [['accept-quotation','accept',z.object({}).strict()],['reject-quotation','reject',z.object({}).strict()],['revisions','revision',revisionSchema],['complete','complete',z.object({}).strict()],['reviews','review',reviewSchema]] as const)app.post(`/api/projects/:id/${path}`,requireRole('CUSTOMER'),async(req,res)=>send(res,await action(req,name,schema.parse(req.body))));
app.use('/api/admin',requireRole('ADMIN'));
app.get('/api/admin/projects',async(req,res)=>send(res,await projectList(req)));
for(const path of ['dashboard','revenue'])app.get(`/api/admin/${path}`,async(req,res)=>send(res,await result(db.rpc('dashboard_report',{actor_id:req.identity.id}))));
app.get('/api/admin/customers',async(req,res)=>send(res,await list(req,db.from('customers').select('*,profiles!inner(full_name,email,role)',{count:'exact'}).eq('profiles.role','CUSTOMER').order('created_at',{ascending:false}),'company_name')));
app.get('/api/admin/customers/:id',async(req,res)=>{const id=uuid.parse(req.params.id);send(res,{customer:await result(db.from('customers').select('*,profiles(full_name,email,phone)').eq('id',id).single()),projects:await list(req,db.from('projects').select('*',{count:'exact'}).eq('customer_id',id).order('created_at',{ascending:false}))})});
app.get('/api/admin/invoices',async(req,res)=>send(res,await list(req,db.from('invoices').select('*',{count:'exact'}).order('issued_at',{ascending:false}))));
app.post('/api/admin/projects/:id/quotation',async(req,res)=>send(res,await action(req,'quotation',quoteSchema.parse(req.body))));
app.patch('/api/admin/projects/:id/status',async(req,res)=>send(res,await action(req,'status',statusSchema.parse(req.body))));
app.post('/api/admin/projects/:id/paid',async(req,res)=>send(res,await action(req,'paid',z.object({}).strict().parse(req.body))));
for(const [table,schema] of Object.entries(resources)){
 app.get(`/api/admin/${table}`,async(req,res)=>send(res,await list(req,db.from(table).select('*',{count:'exact'}).order(table==='testimonials'?'published_at':'created_at',{ascending:false}),table==='testimonials'?'content':table==='portfolio'?'title':'name')));
 app.post(`/api/admin/${table}`,async(req,res)=>{const body=schema.strict().parse(req.body);send(res,await result(db.from(table).insert({...body,...(table==='testimonials'&&'status' in body&&body.status==='APPROVED'?{published_at:new Date().toISOString()}: {})}).select().single()))});
 app.patch(`/api/admin/${table}/:id`,async(req,res)=>{const body=schema.partial().strict().parse(req.body);send(res,await result(db.from(table).update({...body,...(table==='testimonials'&&'status' in body?{published_at:body.status==='APPROVED'?new Date().toISOString():null}:{})}).eq('id',uuid.parse(req.params.id)).select().single()))});
 app.delete(`/api/admin/${table}/:id`,async(req,res)=>{await result(db.from(table).delete().eq('id',uuid.parse(req.params.id)));send(res,{deleted:true})});
}
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:50*1024*1024,files:1,fields:0}});
function fileType(file:Express.Multer.File){const b=file.buffer;const ext=file.originalname.split('.').pop()?.toLowerCase();const valid=(file.mimetype==='image/jpeg'&&['jpg','jpeg'].includes(ext??'')&&b[0]===255&&b[1]===216&&b[2]===255)||(file.mimetype==='image/png'&&ext==='png'&&b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))||(file.mimetype==='image/webp'&&ext==='webp'&&b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP')||(file.mimetype==='application/pdf'&&ext==='pdf'&&b.toString('ascii',0,5)==='%PDF-')||(['video/mp4','video/quicktime'].includes(file.mimetype)&&['mp4','mov'].includes(ext??'')&&b.toString('ascii',4,8)==='ftyp');if(!valid||!b.length)throw new ApiError(422,'INVALID_FILE','Chỉ hỗ trợ JPG, PNG, WEBP, MP4, MOV và PDF hợp lệ (tối đa 50 MB).');return ext;}
for(const [path,bucket,name] of [['/api/projects/:id/files','project-files','file'],['/api/admin/projects/:id/deliverables','deliverables','deliverable']] as const)app.post(path,upload.single('file'),async(req,res)=>{const p=await owned(req);if(bucket==='deliverables'&&req.identity.role!=='ADMIN')throw new ApiError(403,'FORBIDDEN','Không có quyền tải lên.');if(!req.file)throw new ApiError(422,'FILE_REQUIRED','Vui lòng chọn tệp.');const ext=fileType(req.file);const path=`${p.id}/${randomUUID()}.${ext}`;await result(db.storage.from(bucket).upload(path,req.file.buffer,{contentType:req.file.mimetype}));try{await action(req,name,{name:req.file.originalname,path,type:req.file.mimetype,size:req.file.size});}catch(e){await db.storage.from(bucket).remove([path]);throw e}send(res,{path})});
app.get('/api/projects/:id/download/:kind/:fileId',async(req,res)=>{await owned(req);const kind=z.enum(['files','deliverables']).parse(req.params.kind);const row=await result(db.from(kind==='files'?'project_files':'deliverables').select('file_url').eq('id',uuid.parse(req.params.fileId)).eq('project_id',req.params.id).maybeSingle());if(!row)throw new ApiError(404,'NOT_FOUND','Không tìm thấy tệp.');send(res,await result(db.storage.from(kind==='files'?'project-files':'deliverables').createSignedUrl(row.file_url,300,{download:true}))) });
app.post('/api/admin/media',upload.single('file'),async(req,res)=>{if(!req.file)throw new ApiError(422,'FILE_REQUIRED','Vui lòng chọn ảnh.');const ext=fileType(req.file);if(!req.file.mimetype.startsWith('image/'))throw new ApiError(422,'INVALID_FILE','Vui lòng chọn ảnh.');const path=`${randomUUID()}.${ext}`;await result(db.storage.from('portfolio').upload(path,req.file.buffer,{contentType:req.file.mimetype}));send(res,{url:db.storage.from('portfolio').getPublicUrl(path).data.publicUrl})});
app.use((_req,_res,next)=>next(new ApiError(404,'NOT_FOUND','Không tìm thấy đường dẫn.')));
app.use((err:unknown,_req:Request,res:Response,_next:NextFunction)=>{let status=500,code='INTERNAL_ERROR',message='Có lỗi xảy ra. Vui lòng thử lại.';if(err instanceof z.ZodError){status=422;code='VALIDATION_ERROR';message='Thông tin không hợp lệ. Vui lòng kiểm tra các trường.';}else if(err instanceof ApiError){({status,code,message}=err)}else if(err instanceof multer.MulterError){status=422;code='INVALID_UPLOAD';message='Tệp quá lớn hoặc yêu cầu tải lên không hợp lệ.';}else if(err instanceof SyntaxError){status=400;code='INVALID_JSON';message='Dữ liệu gửi lên không hợp lệ.';}else console.error('Unhandled API error',err instanceof Error?err.name:'unknown');res.status(status).json({success:false,error:{code,message}})});
