begin;
create extension if not exists pgcrypto;
create table public.profiles(id uuid primary key default gen_random_uuid(),auth_user_id uuid not null unique references auth.users(id) on delete cascade,role text not null default 'CUSTOMER' check(role in ('CUSTOMER','ADMIN','STAFF')),full_name text not null,email text not null,avatar_url text,phone text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.customers(id uuid primary key default gen_random_uuid(),profile_id uuid not null unique references profiles(id),company_name text,industry text,address text,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.employees(id uuid primary key default gen_random_uuid(),name text not null,email text not null,phone text,position text,department text,skills text[] default '{}',status text default 'ACTIVE' check(status in ('ACTIVE','INACTIVE')),joined_at date,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.services(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,description text,category text,starting_price numeric(16,2) check(starting_price>=0),estimated_days integer check(estimated_days>0),thumbnail_url text,active boolean not null default true,created_at timestamptz default now(),updated_at timestamptz default now());
create table public.projects(id uuid primary key default gen_random_uuid(),customer_id uuid not null references customers(id),title text not null,description text not null,category text,budget numeric(16,2) check(budget>=0),deadline date,status text not null default 'SUBMITTED' check(status in ('DRAFT','SUBMITTED','REVIEWING','QUOTATION_SENT','QUOTATION_ACCEPTED','IN_PROGRESS','WAITING_REVIEW','REVISION','COMPLETED','CANCELLED')),created_at timestamptz default now(),updated_at timestamptz default now());
create table public.project_services(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id) on delete cascade,service_id uuid not null references services(id),quantity integer not null default 1 check(quantity>0),notes text,created_at timestamptz default now(),unique(project_id,service_id));
create table public.quotations(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id),subtotal numeric(16,2) not null,discount numeric(16,2) not null default 0,total numeric(16,2) not null check(total>=0),valid_until date not null,status text not null check(status in ('DRAFT','SENT','ACCEPTED','REJECTED','EXPIRED')),notes text,created_at timestamptz default now(),updated_at timestamptz default now());
create unique index one_live_quote on quotations(project_id) where status in ('SENT','ACCEPTED');
create table public.quotation_items(id uuid primary key default gen_random_uuid(),quotation_id uuid not null references quotations(id) on delete cascade,service_id uuid references services(id),description text not null,quantity integer not null check(quantity>0),unit_price numeric(16,2) not null check(unit_price>=0),total numeric(16,2) not null);
create table public.project_files(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id),uploaded_by uuid not null references profiles(id),file_name text not null,file_url text not null,file_type text not null,file_size bigint not null check(file_size>0),created_at timestamptz default now());
create table public.project_status_history(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id),status text not null,note text,created_by uuid references profiles(id),created_at timestamptz default now());
create table public.deliverables(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id),name text not null,file_url text not null,version integer not null default 1,status text not null default 'PENDING_APPROVAL' check(status in ('UPLOADED','PENDING_APPROVAL','APPROVED','REVISION_REQUIRED')),created_at timestamptz default now(),updated_at timestamptz default now());
create table public.revision_requests(id uuid primary key default gen_random_uuid(),project_id uuid not null references projects(id),customer_id uuid not null references customers(id),description text not null,attachment_url text,status text not null default 'PENDING' check(status in ('PENDING','IN_PROGRESS','RESOLVED','REJECTED')),created_at timestamptz default now(),updated_at timestamptz default now());
create table public.reviews(id uuid primary key default gen_random_uuid(),project_id uuid not null unique references projects(id),customer_id uuid not null references customers(id),rating integer not null check(rating between 1 and 5),quality_rating integer not null check(quality_rating between 1 and 5),communication_rating integer not null check(communication_rating between 1 and 5),value_rating integer not null check(value_rating between 1 and 5),comment text not null,created_at timestamptz default now());
create table public.testimonials(id uuid primary key default gen_random_uuid(),review_id uuid not null unique references reviews(id),content text not null,status text not null default 'PENDING' check(status in ('PENDING','APPROVED','REJECTED')),published_at timestamptz);
create table public.invoices(id uuid primary key default gen_random_uuid(),project_id uuid not null unique references projects(id),customer_id uuid not null references customers(id),invoice_number text not null unique,amount numeric(16,2) not null check(amount>=0),status text not null default 'PENDING' check(status in ('PENDING','PAID','CANCELLED')),issued_at timestamptz default now(),paid_at timestamptz);
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles(id),title text not null,message text not null,type text not null,read_at timestamptz,created_at timestamptz default now());
create table public.portfolio(id uuid primary key default gen_random_uuid(),title text not null,client text not null,description text,category text,image_url text,published boolean not null default false,featured boolean not null default false,created_at timestamptz default now(),updated_at timestamptz default now());
create index projects_customer_idx on projects(customer_id,created_at desc);
create index projects_status_idx on projects(status,created_at desc);
create index invoices_paid_idx on invoices(status,paid_at);
create index notifications_user_idx on notifications(user_id,created_at desc);
do $$ declare t text; begin foreach t in array array['quotations','project_files','project_status_history','deliverables','revision_requests'] loop execute format('create index on public.%I(project_id)',t); end loop; end $$;
create function public.register_profile() returns trigger language plpgsql security definer set search_path=public as $$ declare p uuid; begin insert into profiles(auth_user_id,full_name,email) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','Khách hàng'),new.email) returning id into p; insert into customers(profile_id) values(p); return new; end $$;
create trigger auth_profile after insert on auth.users for each row execute function public.register_profile();
create function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles where auth_user_id=auth.uid() and role='ADMIN') $$;
create function public.owns_project(pid uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from projects p join customers c on c.id=p.customer_id join profiles u on u.id=c.profile_id where p.id=pid and u.auth_user_id=auth.uid() and u.role='CUSTOMER') $$;
do $$ declare t text; begin foreach t in array array['profiles','customers','employees','services','projects','project_services','quotations','quotation_items','project_files','project_status_history','deliverables','revision_requests','reviews','testimonials','invoices','notifications','portfolio'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy admin_all on public.%I for all to authenticated using(public.is_admin()) with check(public.is_admin())',t); end loop; end $$;
create policy own_profile on profiles for select to authenticated using(auth_user_id=auth.uid());
create policy own_profile_update on profiles for update to authenticated using(auth_user_id=auth.uid()) with check(auth_user_id=auth.uid());
revoke update on profiles from authenticated; grant update(full_name,phone,avatar_url) on profiles to authenticated;
create policy own_customer on customers for select to authenticated using(profile_id in(select id from profiles where auth_user_id=auth.uid()));
create policy own_projects on projects for select to authenticated using(owns_project(id));
do $$ declare t text; begin foreach t in array array['project_services','quotations','project_files','project_status_history','deliverables','revision_requests','reviews','invoices'] loop execute format('create policy own_read on public.%I for select to authenticated using(public.owns_project(project_id))',t); end loop; end $$;
create policy own_items on quotation_items for select to authenticated using(exists(select 1 from quotations q where q.id=quotation_id and owns_project(q.project_id)));
create policy own_notifications on notifications for select to authenticated using(user_id in(select id from profiles where auth_user_id=auth.uid()));
create policy public_services on services for select to anon,authenticated using(active);
create policy public_portfolio on portfolio for select to anon,authenticated using(published);
create policy public_testimonials on testimonials for select to anon,authenticated using(status='APPROVED');
-- All business writes go through the authenticated API and its transactional RPC.
create function public.track_project() returns trigger language plpgsql set search_path=public as $$ declare actor uuid; begin
 actor:=nullif(current_setting('app.actor',true),'')::uuid;
 if TG_OP='UPDATE' then
  if new.status=old.status then return new; end if;
  if not ((old.status='DRAFT' and new.status='SUBMITTED') or (old.status='SUBMITTED' and new.status in ('REVIEWING','CANCELLED')) or (old.status='REVIEWING' and new.status in ('QUOTATION_SENT','CANCELLED')) or (old.status='QUOTATION_SENT' and new.status in ('QUOTATION_ACCEPTED','CANCELLED')) or (old.status='QUOTATION_ACCEPTED' and new.status='IN_PROGRESS') or (old.status='IN_PROGRESS' and new.status='WAITING_REVIEW') or (old.status='WAITING_REVIEW' and new.status in ('REVISION','COMPLETED')) or (old.status='REVISION' and new.status='WAITING_REVIEW')) then raise exception 'Chuyển trạng thái không hợp lệ'; end if;
 end if;
 insert into project_status_history(project_id,status,created_by) values(new.id,new.status,actor);
 insert into notifications(user_id,title,message,type) select id,'Cập nhật dự án',new.title||': '||new.status,'PROJECT_STATUS' from profiles where role='ADMIN' or id=(select profile_id from customers where id=new.customer_id);
 return new; end $$;
create trigger project_history after insert or update of status on projects for each row execute function track_project();
create function public.touch_updated() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
do $$ declare t text; begin foreach t in array array['profiles','customers','employees','services','projects','quotations','deliverables','revision_requests','portfolio'] loop execute format('create trigger touch before update on public.%I for each row execute function public.touch_updated()',t); end loop; end $$;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values
 ('project-files','project-files',false,52428800,array['image/jpeg','image/png','image/webp','video/mp4','video/quicktime','application/pdf']),
 ('deliverables','deliverables',false,52428800,array['image/jpeg','image/png','image/webp','video/mp4','video/quicktime','application/pdf']),
 ('avatars','avatars',true,5242880,array['image/jpeg','image/png','image/webp']),
 ('portfolio','portfolio',true,52428800,array['image/jpeg','image/png','image/webp']) on conflict(id) do nothing;
create policy public_media on storage.objects for select to anon,authenticated using(bucket_id in ('avatars','portfolio'));
-- Private objects are delivered by short-lived signed URLs after API ownership checks.
commit;
