begin;
alter table public.services add column featured boolean not null default false;
alter table public.services add column display_order integer not null default 0 check(display_order>=0);
alter table public.services add column features text[] not null default '{}';
alter table public.services add column deliverables text[] not null default '{}';
alter table public.services add column price_max numeric(16,2) check(price_max>=0);
alter table public.services add column seo_title text not null default '';
alter table public.services add column seo_description text not null default '';
alter table public.services add constraint service_price_range check(price_max is null or starting_price is null or price_max>=starting_price);
alter table public.portfolio add column slug text not null default gen_random_uuid()::text;
update public.portfolio set slug=id::text;
create unique index portfolio_slug_idx on public.portfolio(slug);
alter table public.portfolio add column industry text not null default '';
alter table public.portfolio add column year integer check(year between 1900 and 2200);
alter table public.portfolio add column duration text not null default '';
alter table public.portfolio add column challenge text not null default '';
alter table public.portfolio add column solution text not null default '';
alter table public.portfolio add column result text not null default '';
alter table public.portfolio add column gallery text[] not null default '{}';
alter table public.portfolio add column deliverables text[] not null default '{}';
alter table public.portfolio add column seo_title text not null default '';
alter table public.portfolio add column seo_description text not null default '';
create index services_public_order_idx on public.services(active,featured,display_order);
create index portfolio_public_category_idx on public.portfolio(published,category,created_at desc);
commit;
