import { useMemo, useState } from "react";
import { ArrowRight, BadgeCheck, Briefcase, MapPin, Search, ShieldCheck, Star } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { Pagination, State } from "../../components/ui";
import { useApi } from "../../hooks/useApi";
import { useAuth } from "../../contexts/AuthContext";
import { post } from "../../services/api";

type Option = { id: string; name: string; slug: string };
type Creator = { id:string; slug:string; display_name:string; title:string; avatar_url?:string; location:string; rating?:number; review_count:number; completed_projects:number; verified:boolean; featured:boolean; response_time:string; creator_skills:{skills:Option}[]; creator_portfolio:{id:string;title:string;thumbnail_url?:string}[] };
type Collection<T> = { items:T[]; total:number; page:number; limit:number };

export function Creators() {
  const [page,setPage]=useState(1), [search,setSearch]=useState(""), [category,setCategory]=useState(""), [experience,setExperience]=useState(""), [location,setLocation]=useState(""), [sort,setSort]=useState("recommended");
  const options=useApi<{categories:Option[];skills:Option[]}>("/public/creators/filters");
  const path=useMemo(()=>{const p=new URLSearchParams({page:String(page),limit:"6",search,sort}); if(category)p.set("category",category); if(experience)p.set("experience",experience); if(location)p.set("location",location); return `/public/creators?${p}`},[page,search,category,experience,location,sort]);
  const query=useApi<Collection<Creator>>(path);
  const change=(setter:(v:string)=>void)=>(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>{setter(e.target.value);setPage(1)};
  return <main className="creator-page">
    <section className="creator-heading"><small>TRANG CHỦ / <b>TÌM CREATOR</b></small><div><div><h1>Khám phá <span>Creator trẻ &amp; Đội ngũ</span> Sáng tạo</h1><p>Mạng lưới creator được định hướng, kiểm soát quy trình và chịu trách nhiệm sản phẩm cuối cùng bởi MediaHub.</p></div><div className="creator-proof"><strong>100%</strong><span>Đã test tay nghề</span><strong>24/7</strong><span>MediaHub hỗ trợ</span></div></div></section>
    <section className="creator-filter" aria-label="Bộ lọc Creator"><label className="creator-search"><Search size={18}/><input value={search} onChange={change(setSearch)} placeholder="Tìm kỹ năng, tên Creator, phần mềm…"/></label><select aria-label="Chuyên môn" value={category} onChange={change(setCategory)}><option value="">Tất cả chuyên môn</option>{options.data?.categories.map(x=><option key={x.id} value={x.slug}>{x.name}</option>)}</select><label className="location-filter"><MapPin size={16}/><input value={location} onChange={change(setLocation)} placeholder="Toàn quốc / Remote"/></label><select aria-label="Cấp độ" value={experience} onChange={change(setExperience)}><option value="">Cấp độ &amp; Đội ngũ</option><option value="STUDENT">Sinh viên</option><option value="JUNIOR">Junior</option><option value="MID">Middle</option><option value="SENIOR">Senior</option><option value="LEAD">Lead</option></select><button className="btn btn-primary">Tìm kiếm <ArrowRight size={16}/></button><div className="popular-filters"><span>Bộ lọc phổ biến:</span>{options.data?.categories.slice(0,5).map(x=><button className={category===x.slug?"active":""} onClick={()=>{setCategory(category===x.slug?"":x.slug);setPage(1)}} key={x.id}>#{x.name.replaceAll(" ","")}</button>)}<label>Sắp xếp: <select value={sort} onChange={change(setSort)}><option value="recommended">MediaHub đề xuất</option><option value="rating">Đánh giá cao</option><option value="projects">Nhiều dự án</option><option value="price">Giá thấp trước</option></select></label></div></section>
    <section className="creator-results"><div className="results-meta"><span>Hiển thị {query.data?.items.length??0} trong số <b>{query.data?.total??0}+</b> Creator</span><span><ShieldCheck size={15}/> Đảm bảo giao đúng cam kết &amp; nghiệm thu kỹ thuật</span></div><State query={query}><div className="creator-market-grid">{query.data?.items.map(c=><CreatorCard key={c.id} creator={c}/>)}</div>{!query.data?.items.length&&<div className="creator-empty"><Search/><h2>Chưa tìm thấy Creator phù hợp</h2><p>Hãy thử bỏ bớt bộ lọc hoặc tìm bằng kỹ năng khác.</p></div>}<Pagination page={page} total={query.data?.total??0} onChange={setPage}/></State></section>
    <section className="creator-cta"><div><small>QUY TRÌNH MANAGED AGENCY</small><h2>Bạn chưa biết chọn Creator nào để tối ưu ngân sách?</h2><p>Đội ngũ Account &amp; Art Director của MediaHub sẽ tư vấn và chịu trách nhiệm toàn diện từ A–Z.</p></div><Link className="btn btn-primary" to="/request-project">Gửi Brief nhận tư vấn miễn phí <ArrowRight/></Link></section>
  </main>;
}
function CreatorCard({creator:c}:{creator:Creator}) { return <article className={`market-card ${c.featured?"lead":""}`}>{c.featured&&<span className="lead-ribbon">★ MEDIAHUB LEAD CREATOR</span>}<header><img src={c.avatar_url||`https://api.dicebear.com/9.x/initials/svg?seed=${encodeURIComponent(c.display_name)}`} alt={c.display_name}/><div><h2>{c.display_name} {c.verified&&<BadgeCheck size={16}/>}</h2><p>{c.title}</p><small><MapPin size={12}/>{c.location}</small></div><span className="rating"><Star size={13}/> {c.rating??"Mới"}<small>{c.review_count} đánh giá</small></span></header><div className="skill-chips">{c.creator_skills.slice(0,5).map(x=><span key={x.skills.id}>{x.skills.name}</span>)}</div><div className="portfolio-label"><span>Dự án nổi bật</span><b>{c.completed_projects} dự án</b></div><div className="creator-thumbs">{c.creator_portfolio.slice(0,3).map((p,i)=><img key={p.id} src={p.thumbnail_url||`/assets/project-${i+1}.png`} alt={p.title} loading="lazy"/>)}</div><p className="creator-assurance"><ShieldCheck size={16}/> Phối hợp cùng Account Director MediaHub, phản hồi {c.response_time.toLowerCase()}.</p><footer><Link className="btn btn-ghost" to={`/creators/${c.slug}`}><Briefcase size={15}/> Xem Portfolio</Link><MessageCreator creator={c}/></footer></article> }
function MessageCreator({creator}:{creator:Creator}){const nav=useNavigate(),auth=useAuth();const [busy,setBusy]=useState(false);return <button className="btn btn-primary" disabled={busy} onClick={async()=>{if(!auth.currentUser){nav("/login",{state:{from:"/creators"}});return}setBusy(true);try{const conversation=await post("/messages",{creator_id:creator.id,subject:`Trao đổi với ${creator.display_name}`});nav(`/messages/${conversation.id}`)}finally{setBusy(false)}}}>{busy?"Đang mở…":"Nhắn tin"}<ArrowRight size={15}/></button>}
